# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-openai-chat-app-quickstart
metadata:
  template: azure-openai-chat-app-quickstart@0.2.0
requiredVersions:
    azd: ">= 1.10.0"
services:
  aca:
    project: ./src
    language: py
    host: containerapp
    docker:
      remoteBuild: true
pipeline:
  variables:
    - AZURE_OPENAI_CHAT_DEPLOYMENT
    - AZURE_OPENAI_CHAT_MODEL
    - AZURE_OPENAI_CHAT_MODEL_VERSION
    - AZURE_OPENAI_RESOURCE
    - AZURE_OPENAI_RESOURCE_GROUP
    - AZURE_OPENAI_RESOURCE_LOCATION
    - AZURE_OPENAI_DEPLOYMENT_CAPACITY
    - AZURE_OPENAI_DEPLOYMENT_SKU_NAME
    - AZURE_OPENAI_SKU_NAME
    - AZURE_OPENAI_API_VERSION
    - CREATE_AZURE_OPENAI
    - AZURE_OPENAI_ENDPOINT
    - SERVICE_ACA_RESOURCE_EXISTS
    - DISABLE_KEY_BASED_AUTH
